default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bookuser
  password: securepassword
  host: localhost

development:
  <<: *default
  database: book_lending_app_development

test:
  <<: *default
  database: book_lending_app_test

production:
  <<: *default
  database: book_lending_app_production
  username: book_lending_app
  password: <%= ENV["BOOK_LENDING_APP_DATABASE_PASSWORD"] %>
